#!/bin/bash
echo
echo "Building..."
pushd frontend 2>/dev/null
npm run build
popd 2>/dev/null

echo
echo "Replacing master with new build..."
rm -r docs/
cp -r frontend/build docs

echo "Committing the change..."
git add docs/
git commit -m "New build on $(date)"

echo
echo "Done! You can keep programming now!"
