var races = [
   "Aarakocra", "Aasimar / Deva", "Alaghi", "Armand", "Asherati", "Aurak",
   "Aventi", "Azer", "Azurin", "Baaz", "Bariaur", "Beastman", "Bhuka",
   "Bladeling", "Blue (Goblin)", "Bozak", "Bugbear", "Bullywug", "Buomman",
   "Catfolk", "Centaur", "Changeling", "Chaos Gnome", "Chitine", "Crucian",
   "Darfellan", "Deep Imaskarri", "Diopsid", "Drow", "Dire Wereboar (Lycanthrope)",
   "Doppelganger", "Draconic creature", "Dracotaur", "Dragonborn", "Dragonkin",
   "Dromite", "Duergar / Gray Dwarf", "Duskling", "Dvati", "Dwarf", "Eladrin",
   "Elan", "Elf", "Feral Gargun", "Fey'ri", "Firbolg", "Flind", "Fremlin",
   "Frost Giant", "Gargoyle", "Genasi", "Ghost", "Githyanki", "Githzerai",
   "Gloaming", "Gnoll", "Gnome", "Goblin", "Goblinoid", "Goliath", "Grimlock",
   "Hadozee", "Hagspawn", "Half-Celestial", "Half-Dragon", "Half-Elf",
   "Half-Fiend", "Half-Giant", "Half-Ogre", "Half-Orc", "Halfling",
   "Hamadryad", "Hellbred", "Hengeyokai", "Hill Giant", "Hobgoblin", "Human",
   "Illumian", "Jaebrin", "Janni (Genie)", "Kalashtar", "Kapak", "Kender",
   "Kenku", "Killoren", "Kir-Lanan", "Kobold", "Korobokuru", "Kuo-toa", "Lich",
   "Lizardfolk / Lizardman", "Loxo", "Loxodon", "Lupin", "Maenad", "Mephling",
   "Illithid", "Minotaur", "Modron, Rogue", "Mongrelfolk", "Mul",
   "Neanderthal", "Neraphim", "Nezumi", "Ogre", "Orc", "Phrenic creature",
   "Pixie", "Pterran", "Rakasta", "Rakshasa", "Raptoran", "Revenant", "Rilkan",
   "Satyr", "Saurial", "Sea Elf", "Sea Kin", "Shadar-kai", "Shade",
   "Shadowswyft", "Sharakim", "Shardmind", "Shifter", "Simic Hybrid", "Sivak",
   "Skarn", "Skulk", "Slyth", "Spellscale", "Spiker", "Spirit Folk",
   "Stonechild", "Svirfneblin / Deep Gnome", "Swanmay", "Synad", "Tabaxi",
   "Taer", "Tanarukk", "Thri-Kreen", "Tibbit", "Tiefling", "Triton",
   "Troglodyte", "Troll", "Uldra", "Unbodied", "Underfolk", "Vampire",
   "Vanara", "Vedalken", "Verdan", "Voadkyn", "Volodni", "Vryloka",
   "Warforged", "Wemic", "Wilden", "Wildren", "Xeph", "Yuan-t"
]

var classes = [
   "Barbarian/Berserker",
   "Knight/Cavalier",
   "Swashbuckler",
   "Paladin",
   "Dark Knight/Blackguard/Antipaladin/Death Knight",
   "Samurai/Yojimbo/Kensai/Weapon Master",
   "Warlord:General/Tactician/Marshal",
   "Inherent Gift Magician/Sorcerer",
   "Theurgist Magician/Warlock",
   "Summoner Magician/Conjurer",
   "Vancian Magician",
   "The Red Mage",
   "Necromantic Magician",
   "Illusionist Magician",
   "Nature Magician",
   "Elemental Magician",
   "Druid Magician",
   "Shamanic Magician",
   "Thief",
   "Assassin",
   "Gambler",
   "Ninja",
   "Shadow",
   "Pirate/Corsair/Privateer/Swashbuckler",
   "Scout/The Operative",
   "Priest/Healer/White Mage",
   "Battle Priest",
   "Witch Doctor",
   "Templar/Inquisitor",
   "Sniper Ranger",
   "Bow and Blade Ranger",
   "Beastmaster Ranger",
   "Dual Wielding Ranger",
   "Trapper Ranger",
   "Magical Ranger",
   "Hero",
   "Magic Knight",
   "Bard",
   "Dancer",
   "Monk",
   "Engineer",
   "Alchemist",
   "Psychic",
   "Mime/Mimic/Blue Mage",
   "Gunslinger"
]

var physical_traits = [
   "Messy",
   "Fancy",
   "Dyed Hair",
   "Unique eye or hair color",
   "Extremely short or tall",
   "Some discerning physical mark — birthmark, freckles, mole, or scar",
   "Wears unusual glasses",
   "Large feet — may mean they’re clumsy",
   "Bites their nails/lips or chews on their hair",
   "Constantly fidgeting and can’t sit still",
   "Acne, eczema, or other skin problems",
   "Many tattoos or piercings",
   "Often sick or has allergies (constantly sniffling/blowing their nose)",
   "Talks very loudly or quietly",
   "Says everything like it’s a question",
   "Gets sweaty easily (especially when nervous)",
   "Unusually hairy arms or legs",
   "Has a stutter or other speech impediment",
   "Often tucks their hair behind their ears",
   "Smokes and has a raspy voice",
   "Breathes heavily or snores",
   "Is extremely muscular",
   "Walks very slowly or quickly",
   "Left-handed or ambidextrous",
   "Constantly scratching themselves",
   "Has a twitch",
   "Always wears a distinct item of clothing or accessory — a favorite pair of socks, a lucky jersey, or even a particular shade of lipstick"
]

export { physical_traits, classes, races };
